server:
  address: 0.0.0.0

proxy:
  title: OHDSI Evidence Sharing
  logo-url: file:///srv/ohdsi-logo.png
  heartbeat-rate: 30000
  heartbeat-timeout: 900000
  port: 8080
  default-max-instances: 1
  authentication: none
  docker:
      internal-networking: false

  specs:

  - id: 01_SqlDeveloper
    display-name: SqlRender Developer Application
    description: This is the OHDSI SqlRender developer application
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/SqlDeveloper', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/sqldeveloper:1.0.0
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 02_LegendBasicViewer
    display-name: OHDSI Legend basic viewer
    description: This is the OHDSI Legend study basic viewer
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/LegendBasicViewer', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/legendbasicviewer:1.0.0
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 03_OhdsiPredictionTutorial
    display-name: OHDSI Prediction Tutorial
    description: This is the OHDSI Prediction Tutorial
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/OhdsiPredictionTutorial', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/ohdsipredictiontutorial:main
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 04_WhatllHappenToMe
    display-name: Whatll Happen To Me
    description: Find your personalized risk for hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/WhatllHappenToMe', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/whatllhappentome:0.0.5
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 05_HowOften_Andreas
    display-name: How Often Andreas
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_andreas

  - id: 06_HowOften_Azza
    display-name: How Often Azza
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_azza
  
  - id: 07_HowOften_Evan
    display-name: How Often Evan
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_evan

  - id: 08_HowOften_George
    display-name: How Often George
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_george
      
  - id: 09_HowOften_Gowza
    display-name: How Often Gowza
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_gowza
      
  - id: 10_HowOften_Joel
    display-name: How Often Joel
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_joel
            
  - id: 11_HowOften_overall
    display-name: How Often overall
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_overall

  - id: 12_HowOften_Db_diagnostics
    display-name: How Often Db Diagnostics
    description: Database diagnostics for how often study
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften_Db_Diagnostics', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften_db_diagnostics:0.0.1
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      dbDiagnosticsdbSchema: analysis
      
  - id: 13_DiagnosticsExplorerDemo
    display-name: Diagnostics Explorer Demo
    description: Demo of the diagnostics explorer app
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/diagnosticsexplorer:3.2.5

  - id: 14_UveitisSafetyOutcomes
    display-name: Uveitis Safety Outcomes
    description: Cohort Diagnostics
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/outcomes', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/uvetis_safety:1.0.0

  - id: 15_UveitisSafetyIndications
    display-name: Uveitis Safety Indications
    description: Cohort Diagnostics
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/indications', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/uvetis_safety:1.0.0

  - id: 16_PhenotypePhebAlzh
    display-name: Phenotype Phebruary Alzheimers
    description: Cohort Diagnostics
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/phepheb2024:1.0.3
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
      
  - id: 17_PhenotypePhebMdd
    display-name: Phenotype Phebruary MDD
    description: Cohort Diagnostics
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/phepheb2024:1.0.5
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      TABLE_PREFIX: mdd_

  - id: 18_PhenotypePhebPah
    display-name: Phenotype Phebruary PAH
    description: Cohort Diagnostics
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/phepheb2024:1.0.5
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      TABLE_PREFIX: pah_

  - id: 19_SOS_AA
    display-name: SOS 2023 Aortic aneurysm cohorts
    description: Cohort Diagnostics
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/phepheb2024:1.0.5
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      TABLE_PREFIX: sos_aa_

  - id: 20_Semanaion_Char
    display-name: Semaglutide NAION characterization results
    description: Cohort Characterization
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/SemaglutideNaionCharApp', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/semaglutidenaioncharapp:1.0.11
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 21_Semanaion_Est
    display-name: Semaglutide NAION population level estimation results
    description: Population level estimation
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/SemaglutideNaionEstApp', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/semaglutidenaionestapp:1.0.6
    
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
    
  - id: 22_ohdsi_analysis_viewer_app_demo
    display-name: OHDSI Analysis Viewer Demo (2024)
    description: OHDSI Analysis Viewer Demo (2024)
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/OhdsiAnalysisViewerDemoApp', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/ohdsianalysisviewerdemoapp:1.0.2
    
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
    
  - id: 23_TutorialDemo2024
    display-name: OHDSI Tutorial Demo 2024
    description: This is the OHDSI Tutorial demo for 2024
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/TutorialDemo2024', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/tutorialdemo2024:0.0.3
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 24_Glp1Dili
    display-name: GLP-1RA and acute liver injury
    description: Population level estimation
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/Glp1DiliApp', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/glp1diliapp:1.0.5
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 25_EstimationTutorial
    display-name: Estimation Tutorial
    description: CohortMethod and SelfControlledCaseSeries tutorial for population-level estimation
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/EstimationTutorial', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/estimationtutorial:0.0.1
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 26_PhenotypePhebruary2025
    display-name: Phenotype Phebruary 2025
    description: Shiny app for Phenotype Phebruary 2025
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/PhenotypePhebruary2025', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/phenotypephebruary2025:1.0.0
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
