server:
  address: 0.0.0.0

proxy:
  title: OHDSI Evidence Sharing
  logo-url: file:///srv/ohdsi-logo.png
  heartbeat-rate: 30000
  heartbeat-timeout: 180000
  port: 8080
  default-max-instances: 1
  authentication: none
  docker:
      internal-networking: false

  specs:

  - id: 01_SqlDeveloper
    display-name: SqlRender Developer Application
    description: This is the OHDSI SqlRender developer application
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/SqlDeveloper', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/sqldeveloper:1.0.0
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 02_LegendBasicViewer
    display-name: OHDSI Legend basic viewer
    description: This is the OHDSI Legend study basic viewer
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/LegendBasicViewer', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/legendbasicviewer:1.0.0
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 03_OhdsiPredictionTutorial
    display-name: OHDSI Prediction Tutorial
    description: This is the OHDSI Prediction Tutorial
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/OhdsiPredictionTutorial', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/ohdsipredictiontutorial:1.0.1
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 04_WhatllHappenToMe
    display-name: Whatll Happen To Me
    description: Find your personalized risk for hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/WhatllHappenToMe', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/whatllhappentome:0.0.5
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root

  - id: 05_HowOften_Andreas
    display-name: How Often Andreas
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.7
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_andreas

  - id: 06_HowOften_Azza
    display-name: How Often Azza
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.6
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_azza
  
  - id: 07_HowOften_Evan
    display-name: How Often Evan
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.7
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_evan

  - id: 08_HowOften_George
    display-name: How Often George
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.7
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_george
      
  - id: 09_HowOften_Gowza
    display-name: How Often Gowza
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.7
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_gowza
      
  - id: 10_HowOften_Joel
    display-name: How Often Joel
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.7
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_joel
            
  - id: 11_HowOften_overall
    display-name: How Often overall
    description: Incidence of hundreds of outcomes
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften:0.0.7
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      RESULT_DATABASE_SCHEMA: howoften_overall

  - id: 12_HowOften_Db_diagnostics
    display-name: How Often Db Diagnostics
    description: Database diagnostics for how often study
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/HowOften_Db_Diagnostics', host = '0.0.0.0', port = 3838)"]
    container-image: ohdsi/howoften_db_diagnostics:0.0.1
    container-volumes:
      - "/home/jenkins/shinyproxy/.Renviron:/root/.Renviron"
      - "/home/jenkins/minio/data/sp-app-data:/data"
    container-env:
      DATABASECONNECTOR_JAR_FOLDER: /root
      dbDiagnosticsdbSchema: analysis
